### ISSUE TITLE
Bug in "PEOPLE ON BOARD" wiget

### ISSUE THREAD

**Issue by tcgdigital** [tcgdigital/ERSClient#71]
If the KPI values are zero under "PEOPLE ON BOARD" widget, clicking on the value link get exception.

![emergency response system pal]
(https://cloud.githubusercontent.com/assets/25819146/25476947/6addaa54-2b59-11e7-9e54-406fd7df5d19.png)

![image](https://cloud.githubusercontent.com/assets/25819146/25476992/9d2a7a32-2b59-11e7-90f8-9cc469b73a3d.png)

Please resolve the issue.

**Comment by nagsoumittcg** [comment]
Issue resolved.
